### ISSUE TITLE
Unable to run on Openwrt (node v.4.8.0)

### ISSUE THREAD

**Issue by d30jeff** [strongloop/modern-syslog#23]
Hi, 

I have moved my app to a Raspberry PI that has Openwrt installed but I'm getting this error:

```
node: '/root/openwrt-statsmon/node_modules/modern-syslog/build/Release/core.node' is not an ELF executable for ARM
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: File not found
```

Please have a look, thank you.

**Comment by bnoordhuis** [comment]
I'm going to guess you built the module on x86, then copied it to your ARM device.  Run `npm rebuild` on the device.

**Comment by d30jeff** [comment]
Sorry for the delayed response.

I tried running `npm rebuild` and I'm getting this error:

```
root@OpenWrt:~/openwrt-statsmon# npm rebuild

> modern-syslog@1.1.4 install /root/openwrt-statsmon/node_modules/modern-syslog
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/root/openwrt-statsmon/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/root/openwrt-statsmon/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/root/openwrt-statsmon/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/openwrt-statsmon/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/openwrt-statsmon/node_modules/node-gyp/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /root/openwrt-statsmon/node_modules/node-gyp/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.18.36
gyp ERR! command "/usr/bin/node" "/root/openwrt-statsmon/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /root/openwrt-statsmon/node_modules/modern-syslog
gyp ERR! node -v v4.8.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
```

I'm new with `node-gyp`, are there any steps that I should have done before running `npm rebuild`?

Thanks.

**Comment by bnoordhuis** [comment]
A compiler toolchain should be installed before you can build anything: make, g++ >= 4.8.5, binutils.  You're also going to need python2 if it isn't installed already.

**Comment by d30jeff** [comment]
My issues were solved by doing a cross compile/ installation via `npm --arch=arm install <packageName>`

Thanks :+1:
