### ISSUE TITLE
modern-syslog/build/Release/core.node: invalid ELF header

### ISSUE THREAD

**Issue by basickarl** [strongloop/modern-syslog#27]
Was built in a Dockerfile using the node:8 image.

Using version 1.1.4 of modern-syslog.

Trying to use this in a test but it's failing (via docker-compose 3.3):
```
node_1  | > NODE_PATH="$(pwd)" NODE_ENV=test node ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha test/**/*.test.js
node_1  | 
node_1  | =============================================================================
node_1  | Writing coverage object [/opt/www/coverage/coverage.json]
node_1  | Writing coverage reports at [/opt/www/coverage]
node_1  | =============================================================================
node_1  | 
node_1  | =============================== Coverage summary ===============================
node_1  | Statements   : 6.42% ( 7/109 )
node_1  | Branches     : 0% ( 0/36 )
node_1  | Functions    : 0% ( 0/7 )
node_1  | Lines        : 6.48% ( 7/108 )
node_1  | ================================================================================
node_1  | module.js:672
node_1  |   return process.dlopen(module, path._makeLong(filename));
node_1  |                  ^
node_1  | 
node_1  | Error: /opt/www/node_modules/modern-syslog/build/Release/core.node: invalid ELF header
node_1  |     at Object.Module._extensions..node (module.js:672:18)
node_1  |     at Module.load (module.js:556:32)
node_1  |     at tryModuleLoad (module.js:499:12)
node_1  |     at Function.Module._load (module.js:491:3)
node_1  |     at Module.require (module.js:587:17)
node_1  |     at require (internal/module.js:11:18)
node_1  |     at Object.<anonymous> (/opt/www/node_modules/modern-syslog/index.js:9:12)
node_1  |     at Module._compile (module.js:643:30)
node_1  |     at Object.Module._extensions..js (module.js:654:10)
node_1  |     at Object.Module._extensions.(anonymous function) [as .js] (/opt/www/node_modules/istanbul/lib/hook.js:109:37)
node_1  |     at Module.load (module.js:556:32)
node_1  |     at tryModuleLoad (module.js:499:12)
node_1  |     at Function.Module._load (module.js:491:3)
node_1  |     at Module.require (module.js:587:17)
node_1  |     at require (internal/module.js:11:18)
node_1  |     at Object.<anonymous> (/opt/www/application/index.js:9:475)
node_1  |     at Module._compile (module.js:643:30)
node_1  |     at Object.Module._extensions.(anonymous function) [as .js] (/opt/www/node_modules/istanbul/lib/hook.js:107:24)
node_1  |     at Module.load (module.js:556:32)
node_1  |     at tryModuleLoad (module.js:499:12)
node_1  |     at Function.Module._load (module.js:491:3)
node_1  |     at Module.require (module.js:587:17)
node_1  |     at require (internal/module.js:11:18)
node_1  |     at Object.<anonymous> (/opt/www/test/unit.test.js:4:11)
node_1  |     at Module._compile (module.js:643:30)
node_1  |     at Object.Module._extensions..js (module.js:654:10)
node_1  |     at Object.Module._extensions.(anonymous function) [as .js] (/opt/www/node_modules/istanbul/lib/hook.js:109:37)
node_1  |     at Module.load (module.js:556:32)
node_1  |     at tryModuleLoad (module.js:499:12)
node_1  |     at Function.Module._load (module.js:491:3)
node_1  |     at Module.require (module.js:587:17)
node_1  |     at require (internal/module.js:11:18)
node_1  |     at /opt/www/node_modules/mocha/lib/mocha.js:231:27
node_1  |     at Array.forEach (<anonymous>)
node_1  |     at Mocha.loadFiles (/opt/www/node_modules/mocha/lib/mocha.js:228:14)
node_1  |     at Mocha.run (/opt/www/node_modules/mocha/lib/mocha.js:514:10)
node_1  |     at Object.<anonymous> (/opt/www/node_modules/mocha/bin/_mocha:480:18)
node_1  |     at Module._compile (module.js:643:30)
node_1  |     at Object.Module._extensions..js (module.js:654:10)
node_1  |     at Object.Module._extensions.(anonymous function) [as .js] (/opt/www/node_modules/istanbul/lib/hook.js:109:37)
node_1  |     at Module.load (module.js:556:32)
node_1  |     at tryModuleLoad (module.js:499:12)
node_1  |     at Function.Module._load (module.js:491:3)
node_1  |     at Function.Module.runMain (module.js:684:10)
node_1  |     at runFn (/opt/www/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
node_1  |     at /opt/www/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
node_1  |     at /opt/www/node_modules/istanbul/lib/util/file-matcher.js:68:16
node_1  |     at /opt/www/node_modules/async/lib/async.js:52:16
node_1  |     at /opt/www/node_modules/async/lib/async.js:361:13
node_1  |     at /opt/www/node_modules/async/lib/async.js:52:16
node_1  |     at done (/opt/www/node_modules/async/lib/async.js:246:17)
node_1  |     at /opt/www/node_modules/async/lib/async.js:44:16
node_1  |     at /opt/www/node_modules/async/lib/async.js:358:17
node_1  |     at LOOP (fs.js:1745:14)
node_1  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
node_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)
node_1  | npm ERR! code ELIFECYCLE
node_1  | npm ERR! errno 1
node_1  | npm ERR! log@0.0.0 test: `NODE_PATH="$(pwd)" NODE_ENV=test node ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha test/**/*.test.js`
node_1  | npm ERR! Exit status 1
node_1  | npm ERR! 
node_1  | npm ERR! Failed at the log@0.0.0 test script.
node_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node_1  | 
node_1  | npm ERR! A complete log of this run can be found in:
node_1  | npm ERR!     /root/.npm/_logs/2018-03-26T14_12_40_919Z-debug.log
log_node_1 exited with code 1
Aborting on container exit...
```

**Comment by bnoordhuis** [comment]
How did you build it?  The error is clearly saying it was built for a different architecture or OS.  Make sure `file core.node` and `node -p '[process.arch, process.platform]'` agree.

**Comment by basickarl** [comment]
@bnoordhuis Ah you are completely correct, thanks! I was explicitly copying over modern-syslog from the container creating the image. Both which are of different architectures.
